name: selectable_container
description: Selectable container for Flutter. The container shows an icon on one of the corner when tapped.
version: 1.0.3
homepage: https://github.com/fgcan10/selectable_container

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
